[project]
name = "backend"
version = "0.1.0"
description = "E-commerce API (FastAPI + SQLModel + SQLite)"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "fastapi>=0.122.0",
  "sqlmodel>=0.0.27",
  "uvicorn>=0.38.0",
  "passlib[bcrypt]>=1.7.4",
  "python-jose[cryptography]>=3.3.0",
  "psycopg[binary]>=3.2.0",
]

